@echo off
echo Clearing Jest Cache...
call npx jest --clearCache
echo Running Linter...
call npm run lint -- --fix
echo checking types
call npm run typecheck
echo Running Tests...
call npm run test:clean